<a href="https://colab.research.google.com/github/sdg331/BDA/blob/main/06w_dataframe_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 06주차
# 데이터프레임 정보와 검색 활용

## 7.1 데이터프레임 정보와 조건 검색

- csv 파일 읽기
- 데이터프레임 기본 정보 확인
- 합계, 누적합, 평균, 최대/최소 계산
- 조건 검색과 query 사용

### 데이터프레임 준비

- `2016년졸음운전.csv` 파일 사용
- 첫 열을 인덱스로 사용

In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv('/content/2016년졸음운전.csv', encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [27]:
# 기본 통계 정보 확인
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [28]:
# 행과 열을 바꿔서 보기
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [29]:
# 열별 자료형 확인
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [30]:
# 첫 번째 열의 자료형 확인
df.dtypes[0]

/tmp/ipykernel_1742/2839604762.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.dtypes[0]

dtype('int64')

In [31]:
# iloc으로 첫 번째 열의 자료형 확인
df.dtypes.iloc[0]

dtype('int64')

In [32]:
# 데이터프레임 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 684.0+ bytes

### 데이터프레임 합 계산

- `axis=0`: 위에서 아래 방향
- `axis=1`: 왼쪽에서 오른쪽 방향

In [33]:
# 열별 합계
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [34]:
# axis=0은 열별 합계
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [35]:
# 행별 합계
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

### 데이터프레임 누적 합 계산

- `cumsum()` 사용
- 축 방향에 따라 누적 기준이 달라짐

In [36]:
# 위에서 아래 방향 누적합
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [37]:
# 왼쪽에서 오른쪽 방향 누적합
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [38]:
# 여러 데이터프레임을 옆으로 비교 표시
from IPython.display import display_html

def display_side_by_side(*args):
    html_str = ''
    for df in args:
        html_str += df.to_html() + '&nbsp;' * 4
    display_html(html_str.replace('table', 'table style="display:inline"'), raw=True)

In [39]:
# 원본과 행 방향 누적합 비교
display_side_by_side(df, df.cumsum(axis=1))

,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,174,6,328
2016년3월,217,7,435
2016년4월,216,7,419
2016년5월,239,13,522
2016년6월,200,12,362
2016년7월,227,9,460
2016년8월,230,7,490
2016년9월,187,13,347
2016년10월,183,10,367
2016년11월,200,5,418
2016년12월,168,4,364
,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,197,584
2016년2월,174,180,508
2016년3월,217,224,659
2016년4월,216,223,642
2016년5월,239,252,774
2016년6월,200,212,574
2016년7월,227,236,696
2016년8월,230,237,727
2016년9월,187,200,547
2016년10월,183,193,560
2016년11월,200,205,623
2016년12월,168,172,536

In [40]:
# 원본과 열 방향 누적합 비교
display_side_by_side(df, df.cumsum(axis=0))

,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,174,6,328
2016년3월,217,7,435
2016년4월,216,7,419
2016년5월,239,13,522
2016년6월,200,12,362
2016년7월,227,9,460
2016년8월,230,7,490
2016년9월,187,13,347
2016년10월,183,10,367
2016년11월,200,5,418
2016년12월,168,4,364
,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,366,11,715
2016년3월,583,18,1150
2016년4월,799,25,1569
2016년5월,1038,38,2091
2016년6월,1238,50,2453
2016년7월,1465,59,2913
2016년8월,1695,66,3403
2016년9월,1882,79,3750
2016년10월,2065,89,4117
2016년11월,2265,94,4535
2016년12월,2433,98,4899

### 데이터프레임 평균 계산

- `mean()` 사용
- `axis=None`은 전체 평균

In [41]:
# 열별 평균
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [42]:
# 행별 평균
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [43]:
# 전체 평균
df.mean(axis=None)

np.float64(206.38888888888889)

In [44]:
# 원본과 행별 평균 비교
display_side_by_side(df, df.mean(axis=1).to_frame())

### 데이터프레임 최대 최소 계산

- `max()` 최댓값
- `min()` 최솟값

In [45]:
# 열별 최댓값
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [46]:
# 열별 최댓값
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [47]:
# 행별 최댓값
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [48]:
# 전체 최댓값
df.max(axis=None)

522

In [49]:
# 열별 최솟값
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [50]:
# 열별 최솟값
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [51]:
# 행별 최솟값
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [52]:
# 전체 최솟값
df.min(axis=None)

4

In [53]:
# 원본과 행별 최댓값 비교
display_side_by_side(df, df.max(axis=1).to_frame())

In [54]:
# 열별 최댓값과 최솟값 비교
display_side_by_side(df.max().to_frame(), df.min().to_frame())

,0
사고(건),239
사망(명),13
부상(명),522
,0
사고(건),168
사망(명),4
부상(명),328

In [55]:
# 행별 최댓값과 최솟값 비교
display_side_by_side(df.max(axis=1).to_frame(), df.min(axis=1).to_frame())

,0
연월,
2016년1월,387
2016년2월,328
2016년3월,435
2016년4월,419
2016년5월,522
2016년6월,362
2016년7월,460
2016년8월,490
2016년9월,347
2016년10월,367
2016년11월,418
2016년12월,364
,0
연월,
2016년1월,5
2016년2월,6
2016년3월,7
2016년4월,7
2016년5월,13
2016년6월,12
2016년7월,9
2016년8월,7
2016년9월,13
2016년10월,10
2016년11월,5
2016년12월,4

### 데이터프레임 조회

- 특정 열만 선택
- `iloc`으로 열 범위 선택

In [56]:
# 사망과 부상의 합
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [57]:
# iloc으로 사망과 부상 열 선택 후 합
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

### 새로운 열 추가

- 사망자와 부상자 합계로 재해자수 열 생성
- 총계 행 추가

In [58]:
# 원본 복사
df2 = df.copy()
df2

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [59]:
# 재해자수 열 추가
df2['재해자수'] = df2[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [60]:
# 원본과 새 데이터프레임 비교
display_side_by_side(df, df2)

In [61]:
# 열별 합계
df2.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
재해자수     4997
dtype: int64

In [62]:
# 총계 행 추가
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

### 불리안 인덱싱

- 조건 결과는 True, False로 반환
- True인 위치만 선택 가능

In [63]:
# 원소가 10보다 큰지 비교
df2 > 10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [64]:
# True인 원소만 표시
# False 위치는 NaN 표시
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         2433   98.0   4899  4997

In [65]:
# True인 행만 표시
df2[[True] * 6 + [False] * 7]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

### 조건과 isin()

- 조건을 만족하는 행 검색
- `isin()`으로 여러 값 중 하나인지 확인

In [66]:
# 재해자수가 400명 초과인지 확인
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [67]:
# 재해자수가 400명 초과인 행
df2[df2['재해자수'] > 400]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [68]:
# 사망자 수가 7명인지 확인
df2['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
총계          False
Name: 사망(명), dtype: bool

In [69]:
# isin으로 7명인지 확인
df2['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
총계          False
Name: 사망(명), dtype: bool

In [70]:
# 사망자 수가 7명 또는 10명인지 확인
df['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [71]:
# 사망자 수가 7명 또는 10명인 행
df[df['사망(명)'].isin([7, 10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [72]:
# 사망자 수가 7 또는 10이거나 부상자가 350명 초과인 행
df[(df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350)]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [73]:
# 행 이름에 3이 포함된 행
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

### 논리 첨자로 값 대입

- 조건을 만족하는 위치에 값 대입

In [74]:
# 원본 복사
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [75]:
# 10보다 큰 값은 음수로 변경
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

### 함수 df.query(조건)

- 문자열 조건식으로 행 검색
- 열 이름을 바로 사용 가능

In [76]:
# query용 데이터프레임 생성
df = pd.DataFrame({
    'A': range(1, 6),
    'B': range(6, -3, -2),
    'C': range(10, 5, -1),
    'D clmns': range(3, -2, -1),
    'E': ['python', 'java', 'python', 'go', 'python']
})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [77]:
# A가 B보다 큰 행
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [78]:
# 일반 불리안 인덱싱 방식
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [79]:
# C가 10인 행
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [80]:
# A가 0보다 큰 행
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [81]:
# E가 python인 행
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [82]:
# E가 python이 아닌 행
df.query('E != "python"')

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

In [83]:
# 열 이름에 공백이 있으면 백쿼트 사용
df.query('A == `D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [84]:
# 문자열 D clmns와 비교
# 원하는 열 비교 결과가 아님
df.query('A == "D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [85]:
# 일반 방식으로 공백 포함 열 참조
df[df.A == df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [86]:
# or 조건
df.query('A > 3 | B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [87]:
# or 조건
df.query('A > 3 or B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [88]:
# and 조건
df.query('A > 2 & C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [89]:
# and 조건
df.query('A > 2 and C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [90]:
# E가 python 또는 go인 행
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [91]:
# @변수명 사용
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [92]:
# f 문자열 사용
num = 3
df.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [93]:
# 문자열 포함 검색
s = "E.str.contains('py')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [94]:
# g가 포함된 행
s = "E.str.contains('g')"
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go

In [95]:
# on이 포함된 행
s = "E.str.contains('on')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [96]:
# p로 시작하는 행
s = "E.str.startswith('p')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [97]:
# n으로 끝나는 행
s = "E.str.endswith('n')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

## 7.2 데이터프레임 정렬과 수정

- head, tail
- index와 columns 정렬
- 값 기준 정렬
- 열 추가와 값 수정
- 결측값 처리

### 데이터프레임 다시 준비

- 정렬과 수정 실습용 데이터프레임

In [98]:
# csv 파일 다시 읽기
df = pd.read_csv('/content/2016년졸음운전.csv', encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

### df.head(n), df.tail(n)

- 앞부분과 뒷부분 확인

In [99]:
# 앞 5개 행
df.head()

         사고(건)  사망(명)  부상(명)
연월
2016년1월    192      5    387
2016년2월    174      6    328
2016년3월    217      7    435
2016년4월    216      7    419
2016년5월    239     13    522

In [100]:
# 뒤 5개 행
df.tail()

          사고(건)  사망(명)  부상(명)
연월
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [101]:
# 앞 7개 행
df.head(7)

         사고(건)  사망(명)  부상(명)
연월
2016년1월    192      5    387
2016년2월    174      6    328
2016년3월    217      7    435
2016년4월    216      7    419
2016년5월    239     13    522
2016년6월    200     12    362
2016년7월    227      9    460

In [102]:
# 뒤 6개 행
df.tail(6)

          사고(건)  사망(명)  부상(명)
연월
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

### 행 제목으로 정렬

- `sort_index()` 사용
- `ascending=False`는 내림차순

In [103]:
# 행 index 오름차순 정렬
df.sort_index()

          사고(건)  사망(명)  부상(명)
연월
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347

In [104]:
# axis=0 기준 정렬
df.sort_index(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347

In [105]:
# 행 index 내림차순 정렬
df.sort_index(ascending=False)

          사고(건)  사망(명)  부상(명)
연월
2016년9월     187     13    347
2016년8월     230      7    490
2016년7월     227      9    460
2016년6월     200     12    362
2016년5월     239     13    522
2016년4월     216      7    419
2016년3월     217      7    435
2016년2월     174      6    328
2016년1월     192      5    387
2016년12월    168      4    364
2016년11월    200      5    418
2016년10월    183     10    367

### 열 제목으로 정렬

- `axis=1` 사용

In [106]:
# 열 제목 오름차순 정렬
df.sort_index(axis=1)

          부상(명)  사고(건)  사망(명)
연월
2016년1월     387    192      5
2016년2월     328    174      6
2016년3월     435    217      7
2016년4월     419    216      7
2016년5월     522    239     13
2016년6월     362    200     12
2016년7월     460    227      9
2016년8월     490    230      7
2016년9월     347    187     13
2016년10월    367    183     10
2016년11월    418    200      5
2016년12월    364    168      4

In [107]:
# 열 제목 내림차순 정렬
df.sort_index(axis=1, ascending=False)

          사망(명)  사고(건)  부상(명)
연월
2016년1월       5    192    387
2016년2월       6    174    328
2016년3월       7    217    435
2016년4월       7    216    419
2016년5월      13    239    522
2016년6월      12    200    362
2016년7월       9    227    460
2016년8월       7    230    490
2016년9월      13    187    347
2016년10월     10    183    367
2016년11월      5    200    418
2016년12월      4    168    364

### 특정 열의 내용으로 정렬

- `sort_values(by='열명')` 사용

In [108]:
# 사고 건수 기준 오름차순 정렬
df.sort_values(by='사고(건)')

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년2월     174      6    328
2016년10월    183     10    367
2016년9월     187     13    347
2016년1월     192      5    387
2016년11월    200      5    418
2016년6월     200     12    362
2016년4월     216      7    419
2016년3월     217      7    435
2016년7월     227      9    460
2016년8월     230      7    490
2016년5월     239     13    522

In [109]:
# 사고 건수 기준 내림차순 정렬
df.sort_values(by='사고(건)', ascending=False)

          사고(건)  사망(명)  부상(명)
연월
2016년5월     239     13    522
2016년8월     230      7    490
2016년7월     227      9    460
2016년3월     217      7    435
2016년4월     216      7    419
2016년6월     200     12    362
2016년11월    200      5    418
2016년1월     192      5    387
2016년9월     187     13    347
2016년10월    183     10    367
2016년2월     174      6    328
2016년12월    168      4    364

In [110]:
# 사망자 수 기준 오름차순 정렬
df.sort_values(by='사망(명)')

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년1월     192      5    387
2016년11월    200      5    418
2016년2월     174      6    328
2016년8월     230      7    490
2016년4월     216      7    419
2016년3월     217      7    435
2016년7월     227      9    460
2016년10월    183     10    367
2016년6월     200     12    362
2016년5월     239     13    522
2016년9월     187     13    347

In [111]:
# 부상자 수 기준 내림차순 정렬
df.sort_values(by='부상(명)', ascending=False)

          사고(건)  사망(명)  부상(명)
연월
2016년5월     239     13    522
2016년8월     230      7    490
2016년7월     227      9    460
2016년3월     217      7    435
2016년4월     216      7    419
2016년11월    200      5    418
2016년1월     192      5    387
2016년10월    183     10    367
2016년12월    168      4    364
2016년6월     200     12    362
2016년9월     187     13    347
2016년2월     174      6    328

In [112]:
# 여러 열 기준 정렬
df.sort_values(by=['사망(명)', '부상(명)'])

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년1월     192      5    387
2016년11월    200      5    418
2016년2월     174      6    328
2016년4월     216      7    419
2016년3월     217      7    435
2016년8월     230      7    490
2016년7월     227      9    460
2016년10월    183     10    367
2016년6월     200     12    362
2016년9월     187     13    347
2016년5월     239     13    522

In [113]:
# 여러 열 기준 정렬 + 내림차순
df.sort_values(by=['사망(명)', '부상(명)'], ascending=False)

          사고(건)  사망(명)  부상(명)
연월
2016년5월     239     13    522
2016년9월     187     13    347
2016년6월     200     12    362
2016년10월    183     10    367
2016년7월     227      9    460
2016년8월     230      7    490
2016년3월     217      7    435
2016년4월     216      7    419
2016년2월     174      6    328
2016년11월    200      5    418
2016년1월     192      5    387
2016년12월    168      4    364

### 데이터프레임 행 값으로 정렬

- 행 값에 따라 열 순서 정렬
- `axis=1` 사용

In [114]:
# 특정 행 값을 기준으로 열 정렬
df.sort_values(by='2016년1월', axis=1)

          사망(명)  사고(건)  부상(명)
연월
2016년1월       5    192    387
2016년2월       6    174    328
2016년3월       7    217    435
2016년4월       7    216    419
2016년5월      13    239    522
2016년6월      12    200    362
2016년7월       9    227    460
2016년8월       7    230    490
2016년9월      13    187    347
2016년10월     10    183    367
2016년11월      5    200    418
2016년12월      4    168    364

In [115]:
# 특정 행 값을 기준으로 열 내림차순 정렬
df.sort_values(by='2016년1월', axis=1, ascending=False)

          부상(명)  사고(건)  사망(명)
연월
2016년1월     387    192      5
2016년2월     328    174      6
2016년3월     435    217      7
2016년4월     419    216      7
2016년5월     522    239     13
2016년6월     362    200     12
2016년7월     460    227      9
2016년8월     490    230      7
2016년9월     347    187     13
2016년10월    367    183     10
2016년11월    418    200      5
2016년12월    364    168      4

### 데이터프레임 생성과 열명 지정

- 날짜 인덱스 사용
- 난수 데이터프레임 생성

In [116]:
# 날짜 인덱스 생성
dates = pd.date_range('20230101', periods=6)
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')

In [117]:
# 데이터프레임 생성
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2023-01-01  0.260674 -0.676728  1.297325  0.414439
2023-01-02 -2.678750 -0.985805 -0.665813 -1.034145
2023-01-03  1.805635  1.249978 -0.488828 -0.874877
2023-01-04 -0.238311  0.626268  1.310101 -1.582706
2023-01-05  0.557862 -0.700334  0.919127  0.181968
2023-01-06 -3.063398  0.154832 -0.156003  0.678960

### 열 추가

- 시리즈를 새 열에 대입
- 인덱스가 맞지 않으면 NaN 발생

In [118]:
# 열 E에 넣을 시리즈 생성
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20230102', periods=6))
s1

2023-01-02    1
2023-01-03    2
2023-01-04    3
2023-01-05    4
2023-01-06    5
2023-01-07    6
Freq: D, dtype: int64

In [119]:
# E 열 추가
df['E'] = s1
df

                   A         B         C         D    E
2023-01-01  0.260674 -0.676728  1.297325  0.414439  NaN
2023-01-02 -2.678750 -0.985805 -0.665813 -1.034145  1.0
2023-01-03  1.805635  1.249978 -0.488828 -0.874877  2.0
2023-01-04 -0.238311  0.626268  1.310101 -1.582706  3.0
2023-01-05  0.557862 -0.700334  0.919127  0.181968  4.0
2023-01-06 -3.063398  0.154832 -0.156003  0.678960  5.0

### df.loc['행', '열'] = value

- 행과 열 이름으로 값 수정

In [120]:
# loc으로 하나의 값 수정
df.loc[dates[0], 'A'] = 0
df

                   A         B         C         D    E
2023-01-01  0.000000 -0.676728  1.297325  0.414439  NaN
2023-01-02 -2.678750 -0.985805 -0.665813 -1.034145  1.0
2023-01-03  1.805635  1.249978 -0.488828 -0.874877  2.0
2023-01-04 -0.238311  0.626268  1.310101 -1.582706  3.0
2023-01-05  0.557862 -0.700334  0.919127  0.181968  4.0
2023-01-06 -3.063398  0.154832 -0.156003  0.678960  5.0

In [121]:
# loc으로 열 전체 수정
df.loc[:, 'D'] = np.array([5] * len(df))
df

                   A         B         C    D    E
2023-01-01  0.000000 -0.676728  1.297325  5.0  NaN
2023-01-02 -2.678750 -0.985805 -0.665813  5.0  1.0
2023-01-03  1.805635  1.249978 -0.488828  5.0  2.0
2023-01-04 -0.238311  0.626268  1.310101  5.0  3.0
2023-01-05  0.557862 -0.700334  0.919127  5.0  4.0
2023-01-06 -3.063398  0.154832 -0.156003  5.0  5.0

### df.iloc[m, n] = value / df.iat[m, n] = value

- 정수 위치로 값 수정

In [122]:
# iloc으로 하나의 값 수정
df.iloc[0, 1] = 0
df

                   A         B         C    D    E
2023-01-01  0.000000  0.000000  1.297325  5.0  NaN
2023-01-02 -2.678750 -0.985805 -0.665813  5.0  1.0
2023-01-03  1.805635  1.249978 -0.488828  5.0  2.0
2023-01-04 -0.238311  0.626268  1.310101  5.0  3.0
2023-01-05  0.557862 -0.700334  0.919127  5.0  4.0
2023-01-06 -3.063398  0.154832 -0.156003  5.0  5.0

In [123]:
# iat으로 하나의 값 수정
df.iat[0, 2] = 0
df

                   A         B         C    D    E
2023-01-01  0.000000  0.000000  0.000000  5.0  NaN
2023-01-02 -2.678750 -0.985805 -0.665813  5.0  1.0
2023-01-03  1.805635  1.249978 -0.488828  5.0  2.0
2023-01-04 -0.238311  0.626268  1.310101  5.0  3.0
2023-01-05  0.557862 -0.700334  0.919127  5.0  4.0
2023-01-06 -3.063398  0.154832 -0.156003  5.0  5.0

In [124]:
# iloc으로 열 전체 수정
df.iloc[:, 4] = 600
df

                   A         B         C    D      E
2023-01-01  0.000000  0.000000  0.000000  5.0  600.0
2023-01-02 -2.678750 -0.985805 -0.665813  5.0  600.0
2023-01-03  1.805635  1.249978 -0.488828  5.0  600.0
2023-01-04 -0.238311  0.626268  1.310101  5.0  600.0
2023-01-05  0.557862 -0.700334  0.919127  5.0  600.0
2023-01-06 -3.063398  0.154832 -0.156003  5.0  600.0

### 데이터프레임과 DatetimeIndex 생성

- 결측값 처리를 위한 데이터프레임

In [125]:
# 결측값 처리를 위한 데이터프레임 생성
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=list('ABCD'))
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

### 함수 isna()

- 결측값이면 True
- `isnull()`도 같은 기능

In [126]:
# 결측값 확인
df.isna()

       A      B     C      D
0   True  False  True  False
1  False  False  True  False
2   True   True  True   True
3   True  False  True  False

In [127]:
# isnull도 결측값 확인
df.isnull()

       A      B     C      D
0   True  False  True  False
1  False  False  True  False
2   True   True  True   True
3   True  False  True  False

### df.count()

- 결측값이 아닌 값의 개수

In [128]:
# 열마다 결측값이 아닌 개수
df.count()

A    1
B    3
C    0
D    3
dtype: int64

In [129]:
# 행마다 결측값이 아닌 개수
df.count(axis=1)

0    2
1    3
2    0
3    2
dtype: int64

### 함수 value_counts()

- 고유 값 빈도 확인
- `dropna=False`로 NaN 포함

In [130]:
# value_counts 실습용 데이터프레임
df2 = pd.DataFrame({
    '동물': ['고양이', '강아지', '고양이', '토끼', np.nan, '강아지'],
    '색상': ['검정', '흰색', '검정', '회색', '흰색', np.nan]
})
df2

    동물   색상
0  고양이   검정
1  강아지   흰색
2  고양이   검정
3   토끼   회색
4  NaN   흰색
5  강아지  NaN

In [131]:
# 열에서 유일한 값들의 출현 빈도
df2.동물.value_counts()

동물
고양이    2
강아지    2
토끼     1
Name: count, dtype: int64

In [132]:
# 대괄호 방식으로 열 선택 후 value_counts
df2['동물'].value_counts()

동물
고양이    2
강아지    2
토끼     1
Name: count, dtype: int64

In [133]:
# NaN 포함
df2['동물'].value_counts(dropna=False)

동물
고양이    2
강아지    2
토끼     1
NaN    1
Name: count, dtype: int64

In [134]:
# 데이터프레임으로 변환
df2['동물'].value_counts(dropna=False).to_frame()

     count
동물
고양이      2
강아지      2
토끼       1
NaN      1

In [135]:
# 행 조합별 빈도
# 기본은 NaN 제외
df2.value_counts()

동물   색상
고양이  검정    2
강아지  흰색    1
토끼   회색    1
Name: count, dtype: int64

In [136]:
# 행 조합별 빈도
# NaN 포함
df2.value_counts(dropna=False)

동물   색상
고양이  검정     2
강아지  흰색     1
     NaN    1
토끼   회색     1
NaN  흰색     1
Name: count, dtype: int64

### 함수 dropna()

- 결측값이 있는 행 또는 열 제거

In [137]:
# 결측값이 하나라도 있는 행 제거
df2.dropna()

    동물  색상
0  고양이  검정
1  강아지  흰색
2  고양이  검정
3   토끼  회색

In [138]:
# axis=0은 행 제거
df2.dropna(axis=0)

    동물  색상
0  고양이  검정
1  강아지  흰색
2  고양이  검정
3   토끼  회색

In [139]:
# 결측값이 하나라도 있는 열 제거
df2.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

### 결측값에 값 대입

- 논리 인덱싱으로 결측값 수정

In [140]:
# 결측값 위치 확인
df2.isna()

      동물     색상
0  False  False
1  False  False
2  False  False
3  False  False
4   True  False
5  False   True

In [141]:
# 모든 결측값에 500 대입
df2[df2.isna()] = 500
df2

    동물   색상
0  고양이   검정
1  강아지   흰색
2  고양이   검정
3   토끼   회색
4  500   흰색
5  강아지  500

### 결측값을 채우는 함수 fillna()

- 결측값을 지정한 값으로 채움
- 기본은 원본에 바로 반영되지 않음

In [142]:
# 다시 결측값 데이터프레임 생성
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=list('ABCD'))
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [143]:
# 결측값을 10으로 채운 결과
df.fillna(10)

      A     B     C     D
0  10.0   2.0  10.0   0.0
1   3.0   4.0  10.0   1.0
2  10.0  10.0  10.0  10.0
3  10.0   3.0  10.0   4.0

In [144]:
# 원본은 그대로
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [145]:
# 문자열로 결측값 채우기
df.fillna('missing')

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0  missing      1.0
2  missing  missing  missing  missing
3  missing      3.0  missing      4.0

In [146]:
# axis=0 지정
df.fillna('missing', axis=0)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0  missing      1.0
2  missing  missing  missing  missing
3  missing      3.0  missing      4.0

In [147]:
# 각 열에서 최대 1개만 채우기
df.fillna('missing', limit=1)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0      NaN      1.0
2      NaN  missing      NaN  missing
3      NaN      3.0      NaN      4.0

In [148]:
# axis=0에서 limit=1
df.fillna('missing', limit=1, axis=0)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0      NaN      1.0
2      NaN  missing      NaN  missing
3      NaN      3.0      NaN      4.0

In [149]:
# axis=1에서 limit=1
df.fillna('missing', limit=1, axis=1)

         A    B        C    D
0  missing  2.0      NaN  0.0
1      3.0  4.0  missing  1.0
2  missing  NaN      NaN  NaN
3  missing  3.0      NaN  4.0

### fillna(value)

- dict, Series, DataFrame 사용 가능
- 리스트는 대입 불가능

In [150]:
# dict로 열별 대체값 지정
values = {'A': 100, 'B': 200, 'C': 300, 'D': 400}
df.fillna(value=values)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0  300.0  400.0
3  100.0    3.0  300.0    4.0

In [151]:
# 열별 최대 2개만 채우기
df.fillna(value=values, limit=2)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0    NaN  400.0
3    NaN    3.0    NaN    4.0

In [152]:
# Series로 대체값 지정
s = pd.Series([100, 200, 300], index=['A', 'B', 'C'])
df.fillna(s)

       A      B      C    D
0  100.0    2.0  300.0  0.0
1    3.0    4.0  300.0  1.0
2  100.0  200.0  300.0  NaN
3  100.0    3.0  300.0  4.0

In [153]:
# DataFrame으로 대체값 지정
df_value = pd.DataFrame(np.arange(16).reshape(4, 4), columns=list('ABCD'))
df.fillna(df_value)

      A    B     C     D
0   0.0  2.0   2.0   0.0
1   3.0  4.0   6.0   1.0
2   8.0  9.0  10.0  11.0
3  12.0  3.0  14.0   4.0

In [154]:
# 리스트는 value로 사용할 수 없음
df.fillna([100, 200, 300, 400])

TypeError: "value" parameter must be a scalar or dict, but you passed a "list"

### 결측값을 위한 함수 fillna(method='ffill')

- 앞의 값으로 채우기
- 뒤의 값으로 채우기

In [155]:
# 앞의 값으로 채우기
df.fillna(method='ffill')

/tmp/ipykernel_1742/513059541.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

In [156]:
# 앞의 값으로 최대 1개만 채우기
df.fillna(method='ffill', limit=1)

/tmp/ipykernel_1742/2122899233.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=1)

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  NaN  3.0 NaN  4.0

In [157]:
# 뒤의 값으로 최대 1개만 채우기
df.fillna(method='bfill', limit=1)

/tmp/ipykernel_1742/958372072.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', limit=1)

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  3.0 NaN  4.0
3  NaN  3.0 NaN  4.0

In [158]:
# ffill 메소드 사용
df.ffill()

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

In [159]:
# bfill 메소드 사용
df.bfill()

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  3.0 NaN  4.0
3  NaN  3.0 NaN  4.0

### 평균값으로 결측값 채우기

- 열 평균으로 결측값 대체

In [160]:
# 열 평균 확인
df.mean()

A    3.000000
B    3.000000
C         NaN
D    1.666667
dtype: float64

In [161]:
# 각 열의 평균으로 결측값 채우기
df.fillna(df.mean())

     A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

In [162]:
# A부터 B까지의 평균만 사용
df.fillna(df.mean()['A':'B'])

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  3.0 NaN  NaN
3  3.0  3.0 NaN  4.0

In [163]:
# D 열 평균 하나로 모든 결측값 채우기
df.fillna(df.mean()['D'])

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000  1.666667  1.000000
2  1.666667  1.666667  1.666667  1.666667
3  1.666667  3.000000  1.666667  4.000000

In [164]:
# D 열 평균으로 각 열에서 1개만 채우기
df.fillna(df.mean()['D'], limit=1)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [165]:
# axis=0 기준 limit=1
df.fillna(df.mean()['D'], limit=1, axis=0)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [166]:
# axis=1 기준 limit=1
df.fillna(df.mean()['D'], limit=1, axis=1)

          A    B         C    D
0  1.666667  2.0       NaN  0.0
1  3.000000  4.0  1.666667  1.0
2  1.666667  NaN       NaN  NaN
3  1.666667  3.0       NaN  4.0